--- 
- 
  hosts: webservers
  tasks: 
    - 
      name: "Make sure that we can connect to the machine"
    - 
      ping: ~
      tomcat_version: "8.5.53"
    - 
      args: 
        chdir: "/opt/apache-tomcat-{{ tomcat_version }}/bin/"
      become: true
      become_user: tomcat
      name: "Stop Tomcat"
      shell: ./shutdown.sh
    - 
      file: 
        path: "/opt/apache-tomcat-{{ tomcat_version }}"
        state: absent
      name: "Remove Tomcat"
    - 
      name: "remove user \"tomcat\""
      user: 
        name: tomcat
        state: absent
    - 
      group: 
        name: tomcat
        state: absent
      name: "remove group \"tomcat\""
