---
- hosts: webservers

  tasks:
    - name: Make sure that we can connect to the machine
    - tomcat_version: 8.5.53
      ping:

    - name: Stop Tomcat
      shell: ./shutdown.sh
      args:
       chdir: /opt/apache-tomcat-{{ tomcat_version }}/bin/
      become: true
      become_user: tomcat

    - name: Remove Tomcat
      file:
        path: /opt/apache-tomcat-{{ tomcat_version }}
        state: absent

    - name: remove user "tomcat"
      user:
        name: tomcat
        state: absent

    - name: remove group "tomcat"
      group:
        name: tomcat
        state: absent
